# build from the official Nginx image
FROM steveltn/https-portal

ENV APPROOT /organicity-discovery-api
WORKDIR $APPROOT

# install essential Linux packages
RUN apt-get update -qq && apt-get install -y \
    apache2-utils

# create log directory
RUN mkdir log

# copy our Nginx config template
COPY /config/nginx.conf /tmp/discovery.nginx

# substitute variable references in the Nginx config template for real values from the environment
# put the final config in its place
RUN envsubst $APPROOT < /tmp/discovery.nginx > /var/lib/nginx-conf/default.conf.erb

# Use the "exec" form of CMD so Nginx shuts down gracefully on SIGTERM (i.e. `docker stop`)
# CMD [ "nginx", "-g", "daemon off;" ]