# Base image
FROM ubuntu:latest

MAINTAINER Silvia Puglisi <silvia@fablabbcn.org>

WORKDIR /$APPROOT
ENV APPROOT organicity-discovery-api

# establish where image should look for files
ENV RAILS_ROOT /organicity-discovery-api

# Set our working directory inside the image
WORKDIR $RAILS_ROOT

ENV TERM vt100
RUN apt-get update --fix-missing
RUN apt-get  upgrade -y

# Install ruby dependencies
RUN apt-get install  -y wget curl \
    build-essential git git-core \
    zlib1g-dev libssl-dev libreadline-dev \
    libyaml-dev \
    libsqlite3-dev sqlite3 libxml2-dev \
    libxslt1-dev \
    libmysqlclient-dev \
    libffi-dev \
    libffi6 \
    openssh-client \
    supervisor

RUN apt-get update

# Setup ssh key so that tunnel Works
RUN mkdir /root/.ssh
ADD ssh/* /root/.ssh/
RUN cp /root/.ssh/gcocd /root/.ssh/id_rsa &&\
    ls /root/.ssh/  &&\
    ls &&\
    chmod 700 /root/.ssh &&\
    chmod 600 /root/.ssh/* &&\
    chmod 644 ~/.ssh/ssh_config &&\
    ssh-keyscan -t rsa ec2-52-40-19-99.us-west-2.compute.amazonaws.com >> /root/.ssh/known_hosts

EXPOSE 3344
