# Base image
FROM ubuntu:latest

ENV TERM vt100
ENV APPROOT /organicity-discovery-api
WORKDIR $APPROOT

RUN apt-get update && apt-get install -y \
    wget curl \
    build-essential \
    git git-core \
    zlib1g-dev libssl-dev libreadline-dev \
    libyaml-dev \
    libsqlite3-dev sqlite3 libxml2-dev \
    libxslt1-dev \
    libmysqlclient-dev \
    libffi-dev \
    libffi6 \
    openssh-client \
    supervisor

# Setup ssh key so that tunnel Works
RUN mkdir /root/.ssh
COPY /config/ssh/mongo_ssh_key /root/.ssh/gcocd
COPY /config/ssh/mongo_ssh_config /root/.ssh/ssh_config
RUN cp /root/.ssh/gcocd /root/.ssh/id_rsa &&\
    ls /root/.ssh/  &&\
    ls &&\
    chmod 700 /root/.ssh &&\
    chmod 600 /root/.ssh/* &&\
    chmod 644 /root/.ssh/ssh_config &&\
    ssh-keyscan -t rsa dev.orion.organicity.eu >> /root/.ssh/known_hosts

EXPOSE 3344
